INSERT INTO beers 
(name, tagline, description, first_brewed_at, abv, ibu, ebc, ph, volume, ingredients, brewer_tips, created_at, updated_at) 
VALUES
-- === 12 JÁ EXISTENTES ===
('Skol', 'Desce Redondo', 'Pilsen leve, refrescante e de alta drinkabilidade, uma das mais consumidas no Brasil.', DATE '1964-01-01', 4.7, 8, 5, 4.5, 350, 'malte de cevada, milho, lúpulo', 'Mantenha fermentação baixa para perfil neutro.', NOW(), NOW()),
('Brahma', 'O Sabor de Ser Brahmeiro', 'Pilsen clássica brasileira, corpo leve e sabor suave.', DATE '1888-01-01', 4.8, 10, 6, 4.5, 350, 'malte pilsen, arroz, lúpulo', 'Use maturação prolongada para suavidade.', NOW(), NOW()),
('Antarctica', 'A Boa do Brasil', 'Pilsen tradicional, leve e refrescante, bastante popular em todo o país.', DATE '1885-01-01', 4.8, 11, 6, 4.6, 350, 'malte pilsen, cereais não maltados, lúpulo', 'Carbonatação alta aumenta a refrescância.', NOW(), NOW()),
('Heineken', 'Premium Quality', 'Lager puro malte mundialmente conhecida pelo aroma de lúpulo herbal.', DATE '1873-01-01', 5.0, 20, 7, 4.4, 330, 'malte de cevada, lúpulo, água, levedura A-Yeast', 'Fermente lentamente para perfil mais limpo.', NOW(), NOW()),
('Budweiser', 'King of Beers', 'American Lager com arroz, corpo leve e final seco.', DATE '1876-01-01', 5.0, 12, 6, 4.6, 355, 'malte pilsen, arroz, lúpulo', 'Adicione arroz para leveza característica.', NOW(), NOW()),
('Amstel', '100% Malte', 'Lager puro malte com amargor leve e corpo moderado.', DATE '1870-01-01', 4.6, 18, 7, 4.5, 350, 'malte de cevada, lúpulo', 'Fermentação lenta melhora equilíbrio.', NOW(), NOW()),
('Stella Artois', 'Belgian Premium Lager', 'Lager belga refinada com leve amargor floral e final seco.', DATE '1926-01-01', 5.0, 24, 8, 4.5, 330, 'malte pilsen, lúpulo saaz', 'Use lúpulo nobre para aroma floral.', NOW(), NOW()),
('Itaipava', 'Cerveja 100% Verão', 'Pilsen leve e refrescante, muito consumida no Brasil.', DATE '1993-01-01', 4.5, 10, 5, 4.6, 350, 'malte pilsen, milho, lúpulo', 'Carbonate levemente acima do normal.', NOW(), NOW()),
('Corona', 'La Cerveza Más Fina', 'Mexican Lager clara e suave, famosa por ser servida com limão.', DATE '1925-01-01', 4.5, 10, 4, 4.5, 355, 'malte pilsen, arroz, lúpulo', 'Finalize com limão para realçar frescor.', NOW(), NOW()),
('Guinness Draught', 'Irish Dry Stout', 'A stout irlandesa mais famosa do mundo, com notas de café e chocolate.', DATE '1759-01-01', 4.2, 45, 80, 4.2, 440, 'malte torrado, cevada, lúpulo', 'Nitrogenação deixa o corpo mais cremoso.', NOW(), NOW()),
('Snow Beer', 'Cerveja Mais Vendida da China', 'Lager leve, popular na China pelo sabor suave e refrescante.', DATE '1993-01-01', 4.0, 7, 4, 4.6, 330, 'malte pilsen, arroz, lúpulo', 'Use água de baixa mineralidade.', NOW(), NOW()),
('Tsingtao', 'Cerveja Premium Chinesa', 'Lager premium com leve dulçor e aroma herbal.', DATE '1903-01-01', 4.7, 15, 7, 4.5, 330, 'malte pilsen, arroz, lúpulo saaz', 'Mantenha temperaturas baixas para fermentação limpa.', NOW(), NOW()),

-- === 50 NOVAS CERVEJAS ===
('Hoegaarden Witbier', 'The Original Belgian Wheat Beer', 'Cerveja de trigo belga refrescante com notas de coentro e casca de laranja.', DATE \'1445-01-01\', 4.9, 15, 6, 4.6, 330, 'trigo, cevada, coentro, casca de laranja', 'Sirva bem gelada para acentuar o frescor.', NOW(), NOW()),
('Duvel', 'Strong Golden Ale', 'Ale belga forte, dourada e muito aromática.', DATE \'1923-01-01\', 8.5, 32, 10, 4.6, 330, 'malte pilsen, açúcar, lúpulo', 'Fermente duas vezes para perfil complexo.', NOW(), NOW()),
('Leffe Blonde', 'Belgian Abbey Beer', 'Ale belga suave e frutada com notas de banana e especiarias.', DATE \'1240-01-01\', 6.6, 20, 10, 4.5, 330, 'malte, lúpulo, especiarias', 'Use fermentação belga tradicional.', NOW(), NOW()),
('Leffe Brune', 'Rich & Dark Abbey Beer', 'Ale escura e maltada com notas de caramelo.', DATE \'1240-01-01\', 6.5, 22, 35, 4.6, 330, 'maltes escuros, açúcar, lúpulo', 'Maturação prolongada realça dulçor.', NOW(), NOW()),
('Paulaner Weissbier', 'German Wheat Beer', 'Weiss alemã clássica com aroma de banana e cravo.', DATE \'1634-01-01\', 5.5, 12, 8, 4.7, 500, 'trigo maltado, cevada, lúpulo', 'Evite filtrar para manter turbidez.', NOW(), NOW()),
('Erdinger Weissbier', 'Premium Hefeweizen', 'Weiss alemã leve, refrescante e frutada.', DATE \'1886-01-01\', 5.3, 10, 8, 4.7, 500, 'trigo, cevada, lúpulo', 'Sirva em copo alto para espuma ideal.', NOW(), NOW()),
('Spaten Lager', 'German Premium Lager', 'Lager alemã equilibrada, suave e fácil de beber.', DATE \'1397-01-01\', 5.2, 18, 7, 4.7, 500, 'malte pilsen, lúpulo hallertau', 'Mantenha baixa temperatura de maturação.', NOW(), NOW()),
('Beck’s', 'German Quality Beer', 'Lager alemã leve com amargor moderado.', DATE \'1873-01-01\', 5.0, 20, 7, 4.7, 330, 'malte de cevada, lúpulo, água', 'Use lúpulo alemão para aroma herbal.', NOW(), NOW()),
('Patagonia Amber Lager', 'Cerveja da Patagônia', 'Amber Lager encorpada com notas caramelizadas.', DATE \'2010-01-01\', 4.5, 18, 20, 4.5, 740, 'malte caramelo, lúpulo', 'Mantenha amargor baixo.', NOW(), NOW()),
('Patagonia Weisse', 'Cerveja de Trigo da Patagônia', 'Weiss leve com notas cítricas.', DATE \'2015-01-01\', 5.2, 12, 8, 4.6, 740, 'trigo, limão, lúpulo', 'Adicione raspas cítricas no final da fervura.', NOW(), NOW()),
('Colorado Appia', 'Cerveja com Mel', 'Weiss brasileira com adição de mel.', DATE \'2005-01-01\', 5.5, 12, 10, 4.7, 600, 'trigo, cevada, mel', 'Use mel silvestre para aroma floral.', NOW(), NOW()),
('Colorado Indica', 'India Pale Ale Brasileira', 'IPA brasileira com malte caramelizado e amargor intenso.', DATE \'2005-01-01\', 7.0, 45, 18, 4.7, 600, 'malte caramelo, lúpulo americano', 'Dry hopping reforça aroma.', NOW(), NOW()),
('Colorado Demoiselle', 'Porter com Café', 'Porter com café brasileiro, sabor intenso.', DATE \'2008-01-01\', 6.0, 30, 50, 4.4, 600, 'malte torrado, café', 'Use café recém torrado.', NOW(), NOW()),
('Beavertown Gamma Ray', 'American Pale Ale', 'APA explosiva com aroma de frutas tropicais.', DATE \'2011-01-01\', 5.4, 45, 12, 4.5, 330, 'malte, lúpulo citra', 'Dry hopping pesado.', NOW(), NOW()),
('Beavertown Neck Oil', 'Session IPA', 'Session IPA leve e muito aromática.', DATE \'2013-01-01\', 4.3, 35, 10, 4.5, 330, 'malte, lúpulo mosaic', 'Carbonate médio.', NOW(), NOW()),
('Lagunitas IPA', 'A Well-Rounded IPA', 'IPA americana clássica, cítrica e resinosa.', DATE \'1995-01-01\', 6.2, 51, 12, 4.6, 355, 'malte pilsen, lúpulo americano', 'Use dry hopping para aroma intenso.', NOW(), NOW()),
('Lagunitas Little Sumpin\' Sumpin\'', 'Wheat IPA', 'Hoppy Wheat Ale com notas frutadas.', DATE \'2009-01-01\', 7.5, 45, 10, 4.7, 355, 'trigo, cevada, lúpulo', 'Fermentação limpa.', NOW(), NOW()),
('Brooklyn Lager', 'American Amber Lager', 'Amber lager equilibrada com notas florais.', DATE \'1988-01-01\', 5.2, 33, 14, 4.7, 355, 'malte caramelo, lúpulo', 'Fermente lentamente.', NOW(), NOW()),
('Brooklyn IPA', 'East Coast IPA', 'IPA aromática com notas cítricas.', DATE \'1996-01-01\', 7.0, 55, 14, 4.6, 355, 'malte pale ale, lúpulo americano', 'Dry hopping moderado.', NOW(), NOW()),
('Murphy’s Irish Stout', 'Smooth & Creamy Stout', 'Stout irlandesa cremosa, menos amarga que Guinness.', DATE \'1856-01-01\', 4.0, 38, 75, 4.3, 440, 'malte torrado, cevada', 'Nitrogenação baixa.', NOW(), NOW()),
('Kilkenny Irish Cream Ale', 'Creamy Irish Ale', 'Ale cremosa e suave.', DATE \'1710-01-01\', 4.3, 25, 20, 4.5, 440, 'malte pilsen, lúpulo', 'Sirva em pint para formação ideal de espuma.', NOW(), NOW()),
('Chimay Blue', 'Belgian Trappist', 'Strong Dark Ale complexa e encorpada.', DATE \'1956-01-01\', 9.0, 35, 80, 4.5, 330, 'malte escuro, açúcar belga', 'Maturação longa.', NOW(), NOW()),
('Chimay Red', 'Premier Trappist Ale', 'Ale belga frutada e equilibrada.', DATE \'1862-01-01\', 7.0, 33, 35, 4.5, 330, 'malte, lúpulo, fermento belga', 'Servir a 8°C.', NOW(), NOW()),
('Westmalle Tripel', 'The Mother of Tripels', 'Tripel belga dourada e potente.', DATE \'1934-01-01\', 9.5, 38, 10, 4.5, 330, 'malte pilsen, lúpulo', 'Fermente a temperaturas controladas.', NOW(), NOW()),
('Westmalle Dubbel', 'Belgian Dubbel', 'Ale escura belga com notas de frutas secas.', DATE \'1856-01-01\', 7.0, 25, 45, 4.6, 330, 'malte escuro, açúcar', 'Maturação longa.', NOW(), NOW()),
('Tripel Karmeliet', 'Three Grain Tripel', 'Tripel belga com cevada, trigo e aveia.', DATE \'1996-01-01\', 8.4, 20, 10, 4.3, 330, 'cevada, trigo, aveia', 'Fermentação belga tradicional.', NOW(), NOW()),
('Blue Moon', 'Belgian Wheat Ale', 'Witbier americana leve, feita com casca de laranja.', DATE \'1995-01-01\', 5.4, 9, 10, 4.6, 355, 'trigo, coentro, casca de laranja', 'Sirva com rodela de laranja.', NOW(), NOW()),
('Corona Premier', 'Low Carb Lager', 'Versão leve da Corona, refrescante.', DATE \'2018-01-01\', 4.0, 8, 4, 4.5, 355, 'malte, arroz, lúpulo', 'Sirva bem gelada.', NOW(), NOW()),
('Corona Sunbrew', 'Vitamin D Beer', 'Lager com adição de vitamina D.', DATE \'2022-01-01\', 4.0, 8, 4, 4.5, 330, 'malte, arroz, lúpulo', 'Carbonatação alta.', NOW(), NOW()),
('Asahi Super Dry', 'Karankuchi', 'Dry Lager japonesa extremamente limpa e refrescante.', DATE \'1987-01-01\', 5.0, 18, 6, 4.5, 350, 'arroz, malte, lúpulo', 'Fermentação super limpa.', NOW(), NOW()),
('Kirin Ichiban', 'First Press Beer', 'Lager japonesa puro malte com corpo leve.', DATE \'1990-01-01\', 5.0, 21, 7, 4.6, 350, 'malte, lúpulo', 'Use técnica First Press.', NOW(), NOW()),
('Sapporo Premium', 'Japanese Premium Lager', 'Lager japonesa seca e refrescante.', DATE \'1876-01-01\', 4.9, 18, 7, 4.5, 355, 'malte, arroz, lúpulo', 'Sirva bem gelada.', NOW(), NOW()),
('Baltika 7', 'Russian Export Lager', 'Lager russa suave e refrescante.', DATE \'1994-01-01\', 5.4, 20, 7, 4.7, 500, 'malte, arroz, lúpulo', 'Mantenha baixa temperatura.', NOW(), NOW()),
('Baltika 9', 'Strong Lager', 'Lager forte russa, encorpada e alcoólica.', DATE \'1998-01-01\', 8.0, 25, 10, 4.6, 500, 'malte, lúpulo', 'Fermentação lenta.', NOW(), NOW()),
('Tiger Beer', 'World Acclaimed Lager', 'Lager asiática equilibrada.', DATE \'1932-01-01\', 5.0, 18, 7, 4.6, 330, 'malte, arroz, lúpulo', 'Carbonatação média.', NOW(), NOW()),
('Singha', 'Thai Premium Lager', 'Lager tailandesa levemente amarga.', DATE \'1933-01-01\', 5.0, 25, 8, 4.7, 330, 'malte, lúpulo', 'Use lúpulo saaz.', NOW(), NOW()),
('Bud Light', 'Light Lager', 'Versão leve da Budweiser.', DATE \'1982-01-01\', 4.2, 10, 5, 4.6, 355, 'malte, arroz, lúpulo', 'Alta carbonatação.', NOW(), NOW()),
('Michelob Ultra', 'Superior Light Beer', 'Light lager americana muito leve.', DATE \'2002-01-01\', 4.2, 10, 4, 4.6, 355, 'malte, arroz, lúpulo', 'Mantenha seco o final.', NOW(), NOW()),
('Franziskaner Weissbier', 'Premium Hefeweissbier', 'Weiss alemã tradicional e frutada.', DATE \'1872-01-01\', 5.0, 12, 8, 4.6, 500, 'trigo, cevada, lúpulo', 'Servir turva.', NOW(), NOW()),
('Warsteiner Premium', 'German Pilsener', 'Pilsen alemã leve e refrescante.', DATE \'1753-01-01\', 4.8, 30, 6, 4.6, 330, 'malte, lúpulo', 'Use água de baixa mineralidade.', NOW(), NOW()),
('Bitburger', 'Premium Pils', 'Pilsen alemã amarga e crocante.', DATE \'1817-01-01\', 4.8, 38, 6, 4.7, 330, 'malte, lúpulo', 'Fermentação precisa.', NOW(), NOW()),
('Carlsberg', 'Probably the Best Beer', 'Lager dinamarquesa leve e equilibrada.', DATE \'1904-01-01\', 5.0, 20, 7, 4.6, 330, 'malte, lúpulo', 'Sirva bem gelada.', NOW(), NOW()),
('Tuborg', 'Green Beer', 'Lager leve e refrescante.', DATE \'1880-01-01\', 4.6, 18, 6, 4.6, 330, 'malte, lúpulo', 'Carbonatação média.', NOW(), NOW()),
('Bohemia', 'A Primeira do Brasil', 'Pilsen brasileira histórica.', DATE \'1853-01-01\', 4.8, 13, 6, 4.6, 350, 'malte, lúpulo', 'Use água pura.', NOW(), NOW()),
('Original', 'Pilsen Premium', 'Cerveja brasileira refrescante e equilibrada.', DATE \'1931-01-01\', 5.0, 15, 6, 4.6, 600, 'malte, lúpulo', 'Temperatura baixa de serviço.', NOW(), NOW()),
('Serra Malte', 'Puro Malte Nacional', 'Puro malte brasileiro com corpo leve.', DATE \'2005-01-01\', 4.8, 14, 6, 4.6, 600, 'malte pilsen, lúpulo', 'Maturação curta.', NOW(), NOW()),
('Wäls Dubbel', 'Belgian Dubbel Brasileira', 'Dubbel brasileira encorpada.', DATE \'2013-01-01\', 7.5, 25, 40, 4.5, 375, 'maltes escuros, açúcar', 'Maturação longa.', NOW(), NOW()),
('Wäls Session IPA', 'IPA Leve Brasileira', 'Session IPA leve e aromática.', DATE \'2015-01-01\', 4.5, 35, 12, 4.5, 375, 'malte, lúpulo', 'Dry hopping frutado.', NOW(), NOW());
